### ISSUE TITLE
wireclock doesn't wire Clock types

### ISSUE THREAD

**Issue by leonardt** [phanrahan/magma#103]
The current definition doesn't wire `Clock` types, only Reset and Enable. I have to use `wiredefaultclock` for automatically wiring `Clock`s, is this by design?

**Comment by phanrahan** [comment]
Clocks are wired by default in the compiler. We should review the way this is being done.

**Comment by leonardt** [comment]
Does that conflict with having an explicit `wireclock` call wire up the Clock port (that is, if it's wired up by the time it hits default wiring logic in the compiler, does it cause an issue)? 

It seems like if we want to leave the default clock wiring up to the compiler we might want to change the name of `wireclock` as right now the behavior doesn't match the name of the function. Unfortunately I can't think of a better name.

**Comment by leonardt** [comment]
Clock wiring is done internally and this issue has been resolved.
