### ISSUE TITLE
[When] Inferred latches incorrectly detected for array slices

### ISSUE THREAD

**Issue by rsetaluri** [phanrahan/magma#1132]
```python
import magma as m


class _(m.Circuit):
    T = m.Bits[8]
    t_i = m.Out(T)(name="t_i")
    t_o = m.In(T)(name="t_o")
    S = m.Bits[2](name="S")

    with m.when(S[0]):
        t_o @= t_i
    with m.otherwise():
        t_o[:4] @= t_i[4:]
        t_o[4:] @= t_i[4:]
```

I have a feeling this is a tough one to detect...Or the latch methodology may have to consider the flattened values.

**Comment by leonardt** [comment]
This should be handled by the unwire,rewire fix. But, yet basically if there's overlaps we have to check flattened values, that's why the hot fix just forces flattening for arrays.
