### ISSUE TITLE
Ideal Directory Structure

### ISSUE THREAD

**Issue by ankrtlpixxel** [phanrahan/magma#1282]
This is a very basic question.

I wanted to understand the ideal directory structure for the installed files/folders.
- coreIR
- Magma
- miniconda

**While creating new .py file what should be the ideal location of the new file ?**

Below is the current directory structure that I am following.
![structure](https://github.com/phanrahan/magma/assets/120642606/6b7c5287-cbce-473f-b30f-44564899dd72)

**Comment by leonardt** [comment]
I would suggest creating a new directory to hold your project, perhaps using source control like a new git repository.  For simple, single file design, that should be sufficient.  If it's more complex, you may consider using a python package structure, here's a magma specific example: https://github.com/phanrahan/magma/tree/master/examples/riscv_mini that follows the general convention for python package directory structures.  More information on that structure can be found around the web just searching for python package directory structures in general (not magma specific).
