### ISSUE TITLE
Instance Names

### ISSUE THREAD

**Issue by David-Durst** [phanrahan/magma#154]
The current names for Instance ("inst0", "inst1", ...) are very difficult to use when debugging. I had fixed it and undone it because it was causing build failures (https://github.com/phanrahan/magma/pull/150/commits/249a3e6fd13963b9cbcbdf3b276db4ffc08abba5). Ideas on how to fix this without breaking things?

**Comment by leonardt** [comment]
We've since added better instance names using their module as a prefix, we are working on a new feature to automatically capture instance names from the source code (e.g. `x = MyCircuit()` will name the instance 'x')
