### ISSUE TITLE
CircuitKind.__str__ format

### ISSUE THREAD

**Issue by leonardt** [phanrahan/magma#196]
Right now it returns `cls.__name__`, so if we print `mantle.FullAdder`, we get `FullAdder`. We could consider augmenting this with some more useful information, such as including the interface.

Here's one proposal format:
```
>>> print(FullAdder)
FullAdder<I0: In(Bit), I1: In(Bit), CIN: In(Bit), O: Out(Bit), COUT: Out(Bit)>
```

**Comment by phanrahan** [comment]
I agree. How about

FullAdder(I0: In(Bit), I1: In(Bit), CIN: In(Bit), O: Out(Bit), COUT: Out(Bit))

**Comment by leonardt** [comment]
Done via 9649255

**Comment by leonardt** [comment]
(It did break the __repr__ stuff, good catch)
