### ISSUE TITLE
Allow Magma Tuples for IO type

### ISSUE THREAD

**Issue by rdaly525** [phanrahan/magma#240]
It would be nice to be able to write your IO ports like the following:

```
my_type = Tuple(
  a=Out(Bits(5)),
  b=In(Bits(5))
)

class Test(Circuit):
  IO= my_type

  @classmethod
  def definition(io):
    wire(io.a,io.b)
```

It is much more natural to think of the port list as a dictionary rather than an interleaved list of port names and port types. Could we support both?

**Comment by phanrahan** [comment]
This seems reasonable to me. 

Remember that Magma tuples are ordered. We do using function calls where the order of the arguments matter.

**Comment by leonardt** [comment]
Done, added m.IO which basically allows the same pattern
