### ISSUE TITLE
ssa breaks on nested if with returns

### ISSUE THREAD

**Issue by cdonovick** [phanrahan/magma#430]
See https://github.com/phanrahan/magma/blob/ssa-bug/tests/test_ssa/test_ssa.py#L186

**Comment by leonardt** [comment]
This was address in the new ast_tools ssa, so should be fixed by moving to combinational2 (see https://github.com/leonardt/ast_tools/blob/dc73d66d4146aafde1636aa836e90642deceb576/tests/test_ssa.py#L73)
