### ISSUE TITLE
Slicing off the end of an array does not error

### ISSUE THREAD

**Issue by leonardt** [phanrahan/magma#483]
I believe this is because we dispatch to the Python standard slicing logic, which allows slicing off the end of a list, for example:
```
>>> a = [1, 2, 3]
>>> a[1:5]
[2, 3]
```

The proposal is to change the slicing behavior to be more strict and raise an error when the user tries to slice off the end of the array, rather than doing "implicit truncation" like Python's lists.

Let me know if you have objections to this change.

**Comment by phanrahan** [comment]
Seems reasonable to me.
