### ISSUE TITLE
Can't cast to async reset

### ISSUE THREAD

**Issue by jameshegarty** [phanrahan/magma#492]
Casting operator to async reset looks broken?

>class AsyncResetTest(m.Circuit):
>  IO = ['I', m.BitIn, 'O', m.AsyncResetOut ]
>  @classmethod
>   def definition(io):
>   io.O <= m.asyncreset(io.I)

produces:

>ERROR: AsyncResetTest: Cannot wire together
> self.I : Bit
> self.O : coreir.arstIn
>I AM DYING!
>python3: ../src/ir/context.cpp:112: void CoreIR::Context::die(): Assertion `0' failed.
>Aborted (core dumped)`

**Comment by leonardt** [comment]
That looks like a bug, will investigate
