### ISSUE TITLE
Inconsistency with single bit constants

### ISSUE THREAD

**Issue by rdaly525** [phanrahan/magma#499]
I would expect the following code to work. (on branch hwtypes)

```
val = m.Bits[4](0)
assert isinstance(val, m.Bits[4]) #This works

val = m.Bit(0)
assert isinstance(val, m.Bit) #This does not work
```

Why is a single bit constant a 'wire'? Why is this different than a constant Bits?
Given a constant value, is there a consistent way to get its underlying type? (m.Bit for single bit, and m.Bits[n] for multi-bits)

**Comment by phanrahan** [comment]
Not sure why that is. I would say it is a bug.

**Comment by leonardt** [comment]
Is this on the hwtypes branch? This is likely an issue with how VCC/GND are represented (which is returned by Bit(0)).  Agreed this is a bug, but I think the plan is going to be to remove the wire construct and return to the old treatment of values

**Comment by rdaly525** [comment]
Yes, this is on the hwtypes branch. Bit(0) does indeed return GND

**Comment by phanrahan** [comment]
We should make sure isinstance(VCC/GND, Bit) is True.

**Comment by leonardt** [comment]
As of latest master, `VCC` and `GND` are instances of `Digital`, but not `Bit`, however we can make `isinstance(Bit(0), Bit)` and `isinstance(Bit(1), Bit)`, but they will be different than `VCC` and `GND` (we could name them something like `Bit_True` and `Bit_False` or LOW/HIGH.

Alternatively we can revert VCC/GND to be instances of `Bit` and use something else (e.g LOW/HIGH for Digital).

This is simple to implement so it's mainly a matter of choosing the desired name.

**Comment by leonardt** [comment]
Actually, perhaps the simplest current fix is to have VCC be an instance of `Bit` (and therefor an instance of Digital) so it preserves the old naming, and we can decide on how to name 0/1 for digital later.

**Comment by phanrahan** [comment]
Thinking about this in hindsight, I think we should depreciate VCC and GND for values of Bit.

**Comment by leonardt** [comment]
That makes sense to me, there is a bit of logic in the internals that compare VCC/GND to represent 0/1, but instead we can have VCC/GND just be names for the `Bit(0)` and `Bit(1)`
