### ISSUE TITLE
SInt issue with 'hwtypes'

### ISSUE THREAD

**Issue by rdaly525** [phanrahan/magma#501]
in branch 'hwtypes-sint-bug' I have a failing test tests/test_syntax_test_sequential.py:test_sint which shows casting m.Bits to m.SInt does not work as expected. 

The error message is:
`NotImplementedError: (Mux2_x32_inst0.O, <class 'magma.wire.Wire'>)`

Let me know if there is another expected way to cast to SInt/UInt

**Comment by leonardt** [comment]
Is this still an issue with the latest magma? I think since Wire is removed this bug should be no more (hopefully!)

**Comment by rdaly525** [comment]
This was resolved
