### ISSUE TITLE
Invoking pytest on specific file no longer working

### ISSUE THREAD

**Issue by leonardt** [phanrahan/magma#511]
By default pytest supports running a specific test by passing the file, e.g. `pytest tests/test_type/test_conversions.py`.  The recent changes to the test config prevent this from working, any ideas why?

**Comment by rsetaluri** [comment]
See #512. Just decided to move the pycodestyle check out of pytest. Travis still runs it, but its now explicitly a command in .travis.yml, rather than invoked through pytest options. This means that devs must run `pycodestyle magma/` separately (I wanted to avoid this but alas).

**Comment by rsetaluri** [comment]
Resolved by #512
