### ISSUE TITLE
Enum classes are not subclass of magma.Enum

### ISSUE THREAD

**Issue by rdaly525** [phanrahan/magma#548]
```
import magma as m
class A(m.Enum):
  a = 1
  b= 2
assert issubclass(A, m.Enum) #This fails
```

Is there any way to determine if a type is a magma enum?

**Comment by leonardt** [comment]
I'll fix this, but for now, there's an attribute `_is_magma_enum` that you could check https://github.com/phanrahan/magma/blob/e69d0d89a9bf80644f501a7bdb1a5cd440756550/magma/enum.py#L20
