### ISSUE TITLE
_magma_ protocol

### ISSUE THREAD

**Issue by cdonovick** [phanrahan/magma#553]
Its is not possible to encapsulate types and still allow wiring.
Consider:
```Python
class Foo:
    def __init__(self, val: Optional[Bits[8]] = None):
        if val is None: val = Bits[8]()
        self._val = val

    def non_standard_operation(self):
        return Foo((self._val << 2) | (self._val[0] << 1) | self._val[0])
```
While a `Foo` holds a `Bits[8]`  it is not possible to wire it to a `Bits[8]`

In a previous discussion we decided that we would add some sort of protocol to allow types to cast themselves to a magma base type before wire would try to dispatch on them.

**Comment by leonardt** [comment]
We've added basic support this, we can open new issues to track more specific things.
