### ISSUE TITLE
Move ice40 simulator to mantle/lattice/ice40 

### ISSUE THREAD

**Issue by phanrahan** [phanrahan/magma#62]
I think it would make more sense to have the ice40 simulator primitives be part of mantle/lattice/ice40.

We can also test the mantle40 code using the yosys implementations of the ice40 primitives. This would allow is to test the mantle40 implementations using verilator.

**Comment by leonardt** [comment]
I think this done, will move simulating against verilator to a separate mantle issue

https://github.com/phanrahan/mantle/blob/master/mantle/lattice/ice40/simulation.py
