### ISSUE TITLE
Hierarchical sequential circuits that return protocols fail. 

### ISSUE THREAD

**Issue by cdonovick** [phanrahan/magma#671]
See https://github.com/phanrahan/magma/compare/seq-protol-ret

**Comment by rsetaluri** [comment]
[out.txt](https://github.com/phanrahan/magma/files/4441080/out.txt)

Getting this error ^. Seems different than the error you're expecting?

**Comment by rsetaluri** [comment]
See https://github.com/phanrahan/magma/pull/672

**Comment by rsetaluri** [comment]
Closed by #672
