### ISSUE TITLE
Garnet MemTile SData to IData cast issue

### ISSUE THREAD

**Issue by kavyasreedhar** [phanrahan/magma#763]
@leonardt 

I am getting the below errors when running the MemTile code in garnet. They seem related to Magma, but I'm not sure what is causing them. The change between the working code without these errors and what I am running now is that I took out a module that instantiated another module where the first module had no other logic and just connected wires and was essentially unneeded, so nothing functionally changed in the code and the signal types/etc. should match with this new version. Is there anything in particular to look out for that could be causing this error?

I can link to the different versions of code if that's helpful. Thanks!

Running command: make -C obj_dir -j -f VMemCore.mk VMemCore
<STDOUT>
make: Entering directory '/nobackup/skavya/garnet/area/obj_dir'
g++  -I.  -MMD -I/usr/local/share/verilator/include -I/usr/local/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -fcf-protection=none -Wno-bool-operation
 -Wno-sign-compare -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -Wno-shadow       -c -o MemCore_driver.o ../MemCore_driver.cpp
/usr/bin/perl /usr/local/share/verilator/bin/verilator_includer -DVL_INCLUDE_OPT=include VMemCore.cpp VMemCore_commonlib_muxn___05FN16___05Fwidth32.cpp VMemCore__Trace.cpp > VMemCore__ALLfa
st.cpp
/usr/bin/perl /usr/local/share/verilator/bin/verilator_includer -DVL_INCLUDE_OPT=include VMemCore__Syms.cpp VMemCore__Trace__Slow.cpp > VMemCore__ALLslow.cpp
g++  -I.  -MMD -I/usr/local/share/verilator/include -I/usr/local/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -fcf-protection=none -Wno-bool-operation
 -Wno-sign-compare -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -Wno-shadow       -c -o VMemCore__ALLfast.o VMemCore__ALLfast.cpp
g++  -I.  -MMD -I/usr/local/share/verilator/include -I/usr/local/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -fcf-protection=none -Wno-bool-operation
 -Wno-sign-compare -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -Wno-shadow       -c -o VMemCore__ALLslow.o VMemCore__ALLslow.cpp
/usr/local/share/verilator/include/verilated.mk:206: recipe for target 'VMemCore__ALLfast.o' failed
make: Leaving directory '/nobackup/skavya/garnet/area/obj_dir'
</STDOUT>
<STDERR>
In file included from VMemCore__ALLfast.cpp:3:
VMemCore.cpp: In static member function ‘static void VMemCore::_settle__TOP__2(VMemCore__Syms*)’:
VMemCore.cpp:4298:109: error: cast from ‘SData*’ {aka ‘short unsigned int*’} to ‘IData’ {aka ‘unsigned int’} loses precision [-fpermissive]
            | (IData)(vlTOPp->MemCore__DOT__LakeTop_W_inst0__DOT__LakeTop__DOT__strg_ub__DOT__tb_0_col_pixels));
                                                                                                             ^
VMemCore.cpp:4301:110: error: cast from ‘SData*’ {aka ‘short unsigned int*’} to ‘IData’ {aka ‘unsigned int’} loses precision [-fpermissive]
            | ((IData)(vlTOPp->MemCore__DOT__LakeTop_W_inst0__DOT__LakeTop__DOT__strg_ub__DOT__tb_1_col_pixels)
                                                                                                              ^
VMemCore.cpp: In static member function ‘static void VMemCore::_multiclk__TOP__10(VMemCore__Syms*)’:
VMemCore.cpp:14649:110: error: cast from ‘SData*’ {aka ‘short unsigned int*’} to ‘IData’ {aka ‘unsigned int’} loses precision [-fpermissive]
            | ((IData)(vlTOPp->MemCore__DOT__LakeTop_W_inst0__DOT__LakeTop__DOT__strg_ub__DOT__tb_1_col_pixels)
                                                                                                              ^
VMemCore.cpp:14653:109: error: cast from ‘SData*’ {aka ‘short unsigned int*’} to ‘IData’ {aka ‘unsigned int’} loses precision [-fpermissive]
            | (IData)(vlTOPp->MemCore__DOT__LakeTop_W_inst0__DOT__LakeTop__DOT__strg_ub__DOT__tb_0_col_pixels));
                                                                                                             ^
make: *** [VMemCore__ALLfast.o] Error 1
make: *** Waiting for unfinished jobs....
</STDERR>

**Comment by leonardt** [comment]
For anyone running into a similar issue, this was resolved by changing some code that was assigning an unpacked array to a packed array.
