### ISSUE TITLE
sequential2 ite issue with namedtuple + Register combination

### ISSUE THREAD

**Issue by splhack** [phanrahan/magma#778]
a bit tricky

    @m.sequential2()
    class Test:
        def __init__(self):
            self.v = m.Register(T=m.Bit, init=m.bit(0))()

        def __call__(self, sel: m.Bit) -> m.AnonProduct[dict(a=m.Bit)]:
            if sel:
                return m.namedtuple(a=self.v)
            else:
                return m.namedtuple(a=self.v)

Both branches are the same type but `ite` can't handle it

    E           TypeError: ite expects same type for both branches: Tuple(a=<class 'magma.syntax.sequential2._SequentialRegisterWrapperOut(Bit)'>) != Tuple(a=<class 'magma.syntax.sequential2._SequentialRegisterWrapperOut(Bit)'>)

**Comment by leonardt** [comment]
Hmm, maybe this has to do with namedtuple creating a new type and we're not cacheing properly so the type check fails, I'll take a look.
