### ISSUE TITLE
[ergonomics] Mux select expect Bit for depth 2 but Bits[clog2(depth)] otherwise

### ISSUE THREAD

**Issue by leonardt** [phanrahan/magma#825]
This choice makes writing general code based on depth annoying

In this example, we have to unpack the Bit[1] when depth == 2 (mux is implicitly use to dynamically select from the array):
```
class Foo(m.Circuit):
    depth = 2
    N = 8
    data_out_array = m.Array[depth, m.Bits[N]](name="foo")
    ptr_width = m.bitutils.clog2(depth)
    ptr = m.Register(m.Bits[ptr_width])()
    data = data_out_array[ptr.O[0] if ptr_width == 1 else ptr.O]
```

If magma handles this conversion internally (e.g. in the logic of the mux), then the user code is simpler, otherwise the user has to make this ternary conversion any time this pattern appears.

**Comment by rsetaluri** [comment]
Good point. Figure a simple fix is to make the mux just be flexible over select. I'm also working on a smart bits version of mux which may also solve this problem.
