### ISSUE TITLE
@m.combinational2 got TypeError : unsupported operand type(s) for +: 'function' and 'list'

### ISSUE THREAD

**Issue by timacro** [phanrahan/magma#982]
I start learning magma with this simple code in REPL:

```python
import magma as m

@m.combinational2
def ternary(I: m.Bits[2], S: m.Bit) -> m.Bit:
    return I[0] if S else I[1]
```

but got a error:
TypeError: unsupported operand type(s) for +: 'function' and 'list'

My python version is 3.8.5 and magma-lang version is 2.1.48. 

Could you point out the problem ?  Thanks!

**Comment by timacro** [comment]
Oh i get it, should be `@m.combinational2()`

**Comment by rsetaluri** [comment]
@timacro glad you got this resolved!
